# Generated by Django 3.2 on 2023-04-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(db_column='seat_number')),
            ],
            options={
                'db_table': 'seats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField(db_column='date_of_booking')),
                ('coach_id', models.CharField(db_column='coach_id', max_length=10)),
                ('number_of_seats', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], db_column='number_of_seats')),
                ('seat_numbers', models.ForeignKey(db_column='seat_numbers', on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='booking_management.seats')),
            ],
            options={
                'db_table': 'booking_details',
                'managed': True,
                'unique_together': {('date_of_booking', 'seat_numbers', 'coach_id')},
            },
        ),
    ]
