# Generated by Django 3.2 on 2023-04-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0002_bookingdetails_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_number',
            field=models.IntegerField(db_column='seat_number', unique=True),
        ),
    ]
