# Generated by Django 3.2 on 2023-04-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0003_alter_seats_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='booked_id',
            field=models.ForeignKey(db_column='booked_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_id', to='booking_management.bookingdetails'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingdetails',
            unique_together={('date_of_booking', 'coach_id')},
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='seat_numbers',
        ),
    ]
