# Generated by Django 3.2 on 2023-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0004_auto_20230426_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_number',
            field=models.IntegerField(db_column='seat_number'),
        ),
    ]
