# Generated by Django 3.2 on 2023-04-26 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0006_seats_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='date',
            field=models.DateField(db_column='date', default=datetime.date(2023, 4, 26)),
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('date', 'seat_number', 'booked_id')},
        ),
    ]
