# Generated by Django 3.2 on 2023-04-26 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0007_auto_20230426_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='date',
            field=models.DateField(db_column='date', default=datetime.datetime(2023, 4, 26, 9, 15, 37, 116435, tzinfo=utc)),
        ),
    ]
