# Generated by Django 3.2 on 2023-04-26 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0008_alter_seats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='date',
            field=models.DateField(db_column='date', default=datetime.date.today),
        ),
    ]
