# Generated by Django 3.2 on 2023-04-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0009_alter_seats_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingdetails',
            unique_together=set(),
        ),
    ]
