# Generated by Django 3.2 on 2023-04-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0010_alter_bookingdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('date', 'seat_number')},
        ),
    ]
